### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [IoT-Coder/MMM-ShellyPlus-HT#1]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: <https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md> :slightly_smiling_face: 

By the way: Without a license your module can't be displayed with a screenshot on [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

**Comment by IoT-Coder** [comment]
Thanks for the hint ! I did not think about that so far .....
Added now the MIT license file.

**Comment by KristjanESPERANTO** [comment]
Nice. Now the screenshot is displayed in the new module list :rocket: Thanks for the quick reaction! :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
Ah one thing: In the copyright line should be your name :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
Your alias "IoT-Coder" should work to.
